name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  dockerimage-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for my python-api 
      run: docker build -t jagadish8054/ci-cd-python-api-testing:2.0 .
    - name:  docker  login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name:  docker push the image
      run : docker push ${{ secrets.DOCKER_USERNAME}}/ci-cd-python-api-testing:2.0 
    
